sudo: required
services:
  - docker

before_install:
  - docker build -t assaf007/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true assaf007/docker-react npm run test -- --colors --coverage --watchAll=false