sudo: required
services:
  - docker

before_install:
  - docker build -t assaf007/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true assaf007/docker-react npm run test -- --colors --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-688121820106"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"